---


'.test_common': &job_test_common
  script:
    - 'python3 -m pip install --upgrade pip setuptools'
    - 'python3 -m pip install --upgrade tox'
    - 'python3 -m tox'
    - 'python3 -m tox -e package'

'test py35':
  <<: *job_test_common
  image: 'python:3.5'
  variables:
    'TOXENV': 'py35'

'test py36':
  <<: *job_test_common
  image: 'python:3.6'
  variables:
    'TOXENV': 'py36'

'test py37':
  <<: *job_test_common
  image: 'python:3.7'
  variables:
    'TOXENV': 'py37'

'test py38 dev':
  <<: *job_test_common
  image: 'python:3.8-rc'
  variables:
    'TOXENV': 'py38'


... EOF
